// Package types defines data structures and types used throughout the system
package types

import (
	"database/sql/driver"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// History represents a conversation history entry
// Contains query-answer pairs and associated knowledge references
// Used for tracking conversation context and history
type History struct {
	Query               string     // User query text
	Answer              string     // System response text
	CreateAt            time.Time  // When this history entry was created
	KnowledgeReferences References // Knowledge references used in the answer
}

// MentionedItem represents a mentioned knowledge base or file
type MentionedItem struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Type   string `json:"type"`    // "kb" for knowledge base, "file" for file
	KBType string `json:"kb_type"` // "document" or "faq" (only for kb type)
}

// MessageImage represents an image attached to a chat message
type MessageImage struct {
	URL     string `json:"url"`
	Caption string `json:"caption,omitempty"`
}

// MessageImages is a slice of MessageImage for database storage
type MessageImages []MessageImage

// Value implements the driver.Valuer interface for database serialization
func (m MessageImages) Value() (driver.Value, error) {
	if m == nil {
		return json.Marshal([]MessageImage{})
	}
	return json.Marshal(m)
}

// Scan implements the sql.Scanner interface for database deserialization
func (m *MessageImages) Scan(value interface{}) error {
	if value == nil {
		*m = make(MessageImages, 0)
		return nil
	}
	var b []byte
	switch v := value.(type) {
	case []byte:
		b = v
	case string:
		b = []byte(v)
	default:
		*m = make(MessageImages, 0)
		return nil
	}
	return json.Unmarshal(b, m)
}

// MentionedItems is a slice of MentionedItem for database storage
type MentionedItems []MentionedItem

// Value implements the driver.Valuer interface for database serialization
func (m MentionedItems) Value() (driver.Value, error) {
	if m == nil {
		return json.Marshal([]MentionedItem{})
	}
	return json.Marshal(m)
}

// Scan implements the sql.Scanner interface for database deserialization
func (m *MentionedItems) Scan(value interface{}) error {
	if value == nil {
		*m = make(MentionedItems, 0)
		return nil
	}
	var b []byte
	switch v := value.(type) {
	case []byte:
		b = v
	case string:
		b = []byte(v)
	default:
		*m = make(MentionedItems, 0)
		return nil
	}
	return json.Unmarshal(b, m)
}

// Message represents a conversation message
// Each message belongs to a conversation session and can be from either user or system
// Messages can contain references to knowledge chunks used to generate responses
type Message struct {
	// Unique identifier for the message
	ID string `json:"id"                    gorm:"type:varchar(36);primaryKey"`
	// ID of the session this message belongs to
	SessionID string `json:"session_id"`
	// Request identifier for tracking API requests
	RequestID string `json:"request_id"`
	// Message text content
	Content string `json:"content"`
	// Message role: "user", "assistant", "system"
	Role string `json:"role"`
	// References to knowledge chunks used in the response
	KnowledgeReferences References `json:"knowledge_references"  gorm:"type:json,column:knowledge_references"`
	// Agent execution steps (only for assistant messages generated by agent)
	// This contains the detailed reasoning process and tool calls made by the agent
	// Stored for user history display, but NOT included in LLM context to avoid redundancy
	AgentSteps AgentSteps `json:"agent_steps,omitempty" gorm:"type:jsonb,column:agent_steps"`
	// Mentioned knowledge bases and files (for user messages)
	// Stores the @mentioned items when user sends a message
	MentionedItems MentionedItems `json:"mentioned_items,omitempty" gorm:"type:jsonb,column:mentioned_items"`
	// Attached images with OCR/Caption text (for user messages)
	Images MessageImages `json:"images,omitempty" gorm:"type:jsonb;column:images"`
	// Whether message generation is complete
	IsCompleted bool `json:"is_completed"`
	// Whether this response is a fallback (no knowledge base match found)
	IsFallback bool `json:"is_fallback,omitempty"`
	// Agent total execution duration in milliseconds (from query start to answer start)
	AgentDurationMs int64 `json:"agent_duration_ms,omitempty" gorm:"column:agent_duration_ms;default:0"`
	// RenderedContent stores the full RAG-augmented user message (with retrieved context)
	// sent to the LLM. Used to preserve retrieval context across conversation turns.
	// Empty for non-retrieval intents or assistant messages.
	RenderedContent string `json:"-" gorm:"type:text;column:rendered_content;default:''"`
	// Channel indicates the source channel of this message (e.g., "web", "api", "im")
	Channel string `json:"channel,omitempty" gorm:"type:varchar(50);default:''"`
	// Feedback stores user quality signal: "" (none), "like", or "dislike"
	Feedback string `json:"feedback,omitempty" gorm:"type:varchar(10);default:''"`
	// KnowledgeID links this message to a Knowledge entry in the chat history knowledge base
	// Used for vector search indexing: when set, the message content has been indexed as a Knowledge passage
	KnowledgeID string `json:"knowledge_id,omitempty" gorm:"type:varchar(36);index"`
	// Message creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at"`
	// Soft delete timestamp
	DeletedAt gorm.DeletedAt `json:"deleted_at"            gorm:"index"`
}

// AgentSteps represents a collection of agent execution steps
// Used for storing agent reasoning process in database
type AgentSteps []AgentStep

// Value implements the driver.Valuer interface for database serialization
func (a AgentSteps) Value() (driver.Value, error) {
	if a == nil {
		return json.Marshal([]AgentStep{})
	}
	return json.Marshal(a)
}

// Scan implements the sql.Scanner interface for database deserialization
func (a *AgentSteps) Scan(value interface{}) error {
	if value == nil {
		*a = make(AgentSteps, 0)
		return nil
	}
	var b []byte
	switch v := value.(type) {
	case []byte:
		b = v
	case string:
		b = []byte(v)
	default:
		*a = make(AgentSteps, 0)
		return nil
	}
	return json.Unmarshal(b, a)
}

// BeforeCreate is a GORM hook that runs before creating a new message record
// Automatically generates a UUID for new messages and initializes knowledge references
// Parameters:
//   - tx: GORM database transaction
//
// Returns:
//   - error: Any error encountered during the hook execution
func (m *Message) BeforeCreate(tx *gorm.DB) (err error) {
	m.ID = uuid.New().String()
	if m.KnowledgeReferences == nil {
		m.KnowledgeReferences = make(References, 0)
	}
	if m.AgentSteps == nil {
		m.AgentSteps = make(AgentSteps, 0)
	}
	if m.MentionedItems == nil {
		m.MentionedItems = make(MentionedItems, 0)
	}
	if m.Images == nil {
		m.Images = make(MessageImages, 0)
	}
	return nil
}

// MessageSearchMode represents the search mode for message search
type MessageSearchMode string

const (
	// MessageSearchModeKeyword searches by keyword only
	MessageSearchModeKeyword MessageSearchMode = "keyword"
	// MessageSearchModeVector searches by vector similarity only
	MessageSearchModeVector MessageSearchMode = "vector"
	// MessageSearchModeHybrid combines keyword and vector search with RRF fusion
	MessageSearchModeHybrid MessageSearchMode = "hybrid"
)

// MessageSearchParams defines the parameters for searching chat history messages
type MessageSearchParams struct {
	// Query text for search
	Query string `json:"query" binding:"required"`
	// Search mode: "keyword", "vector", "hybrid" (default: "hybrid")
	Mode MessageSearchMode `json:"mode"`
	// Maximum number of results to return (default: 20)
	Limit int `json:"limit"`
	// Filter by specific session IDs (optional, empty means all sessions)
	SessionIDs []string `json:"session_ids"`
}

// MessageWithSession extends Message with session title for search results
type MessageWithSession struct {
	Message
	// Title of the session this message belongs to
	SessionTitle string `json:"session_title"`
}

// MessageSearchResultItem represents a single search result item (internal, pre-merge)
type MessageSearchResultItem struct {
	// The matched message with session info
	MessageWithSession
	// Search relevance score (higher is better)
	Score float64 `json:"score"`
	// How this result was matched: "keyword", "vector", or "hybrid"
	MatchType string `json:"match_type"`
}

// MessageSearchGroupItem represents a merged Q&A pair in search results.
// Messages sharing the same request_id are grouped together so that the user query
// and assistant answer are displayed side by side.
type MessageSearchGroupItem struct {
	// The request_id that groups Q&A together
	RequestID string `json:"request_id"`
	// Session info
	SessionID    string `json:"session_id"`
	SessionTitle string `json:"session_title"`
	// User query content (role=user)
	QueryContent string `json:"query_content"`
	// Assistant answer content (role=assistant), may be empty if only Q matched
	AnswerContent string `json:"answer_content"`
	// Best score among the matched messages in this group
	Score float64 `json:"score"`
	// How this result was matched: "keyword", "vector", or "hybrid"
	MatchType string `json:"match_type"`
	// Timestamp of the earliest message in the group
	CreatedAt time.Time `json:"created_at"`
}

// MessageSearchResult represents the search result for message search
type MessageSearchResult struct {
	// List of merged Q&A pairs
	Items []*MessageSearchGroupItem `json:"items"`
	// Total number of results
	Total int `json:"total"`
}

// ChatHistoryKBStats represents statistics about the chat history knowledge base
type ChatHistoryKBStats struct {
	// Whether the chat history KB is configured and enabled
	Enabled bool `json:"enabled"`
	// ID of the embedding model used
	EmbeddingModelID string `json:"embedding_model_id,omitempty"`
	// ID of the knowledge base used for chat history
	KnowledgeBaseID string `json:"knowledge_base_id,omitempty"`
	// Name of the knowledge base
	KnowledgeBaseName string `json:"knowledge_base_name,omitempty"`
	// Number of indexed message entries (Knowledge count)
	IndexedMessageCount int64 `json:"indexed_message_count"`
	// Whether there are any indexed messages (used by frontend to lock embedding model)
	HasIndexedMessages bool `json:"has_indexed_messages"`
}
